### ISSUE TITLE
Z-Score: Enhancements and Bug Fix

### ISSUE THREAD

**Issue by cbueth** [cbueth/delaynet#14]
### Description:
We need to make a few enhancements to the Z-Score normalization function and fix a bug in the vectorized version of the function.

### To-Do:

- [x] **Enhancement:** Add an additional parameter `max_periods` to the Z-Score normalization function. This parameter will determine the number of periods that can be considered before and after the current point when calculating the Z-Score. For example, if we're processing point #100, and the periodicity is 10, setting `max_periods` to 1 would only calculate the mean and standard deviation of values 90 and 110. Setting it to 2 would consider values 80, 90, 110, 120.

- [x] **Enhancement:** The value being analyzed should not be included in the calculation of the average and standard deviation. For example, if we're processing point #100, this value should not be included in the calculations.

- [ ] **Bug Fix:** Fix the `ValueError: cannot reshape array of size 10000 into shape (24)` error in line 46 of the vectorized version of the Z-Score normalization function.

### Files to be modified:
- `delaynet/norms/z_score.py`

### Additional Context:
These enhancements and bug fix are based on feedback and testing.
