### ISSUE TITLE
Implement Pre-check for Entropy Based Connectivities

### ISSUE THREAD

**Issue by cbueth** [cbueth/delaynet#18]
### Description:
In entropy-based connectivity metrics such as Mutual Information (MI) and Transfer Entropy (TE), the input time series need to be symbolic, i.e., they should have a limited set of input "symbols". Currently, there is no check in place to ensure this.

### Task:
Implement a pre-check in the connectivity decorator that verifies whether the input time series are symbolic. If they are not, the decorator should either raise an error or apply a pre-processing method to convert the time series into a symbolic form.

### Acceptance Criteria:
- [x] The connectivity decorator should include a pre-check for symbolic time series.
- [x] If the input time series are not symbolic, an error should be raised or a pre-processing method should be applied.
- [ ] The implementation should be tested with various types of time series data to ensure its correctness.

### Example
Accepting only integer arrays with a limited set of symbols:
```python3
import numpy as np

def check_symbolic(array, max_symbols):
    """
    Check if a numpy array is symbolic.

    :param array: The numpy array to check.
    :type array: ndarray
    :param max_symbols: The maximum number of unique symbols allowed.
    :type max_symbols: int
    :raises ValueError: If the array is not symbolic.
    """
    if array.dtype.kind == 'f':
        raise ValueError("Input array cannot be of float type.")
    elif array.dtype.kind in 'iu':
        unique_symbols = np.unique(array)
        if len(unique_symbols) > max_symbols:
            raise ValueError(f"Input array has more than {max_symbols} unique symbols.")
    else:
        raise ValueError("Input array must be of integer type.")
```

Next: #19
